leukaemia_classes = [
    'Postac nie T i nie B',
    'Postac T',
    'Postac B',
    'Mieloblastyczna o niskim niezroznicowaniu',
    'Mieloblastyczna z dojrzewaniem',
    'Promielocytowa',
    'Mielomonoblastyczna',
    'Monoblastyczna',
    'Erytroleukemia',
    'Podostra granulocytarna',
    'Granulocytarna',
    'Limfocytarna',
    'Mielomonocytarna',
    'Monocytarna',
    'Chloniak limfatyczny bialaczka',
    'Plazmocytowa',
    'Wielokapilarnokomórkowa',
    'Eozynofilowa',
    'Bazofilowa',
    'Bialaczka komorek wielkojadrzastych',
]

leukaemia_features = [
    # 'IDKlasy',
    # 'ID',
    'Temperatura',
    'Anemia',
    'Stopien krwawienia',
    'Miejsce krwawienia',
    'Bole kosci',
    'Wrazliwosc mostka',
    'Powiekszenie wezlow chlonnych',
    'Powiekszenie watroby i sledziony',
    'Centralny uklad nerwowy',
    'Powiekszenie jader',
    'Uszkodzenie w secu plucach nerce',
    'Galka oczna',
    'Poziom WBC',
    'Obnizenie liczby RBC',
    'Liczba plytek krwi',
    'Niedojrzale komorki (blastyczne)',
    'Stan pobudzenia szpiku',
    'Glowne komorki w szpiku',
    'Poziom limfocytow',
    'Reakcja'
]

csv_file_path = 'data/bialaczka.csv'
